---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: hw_virtualization_check | load cpu info
  become: true
  slurp:
    src: /proc/cpuinfo
  register: cpu_info

- name: hw_virtualization_check | idenitfy hw virtualization support
  set_fact:
    libvirt_domain_type: "{{
      cpu_info['content'] | b64decode |
      regex_search('(vmx|svm)', multiline=True) |
      ternary('kvm', 'qemu') }}"

- name: install dependency
  package:
    name: "{{ libvirt_dependecies }}"
    state: present
  when:
    - libvirt_dependecies is defined
    - libvirt_dependecies | count > 0


- name: merge libvirtd config configuration between defaults and custom
  set_fact:
    libvirt_libvirtd: "{{ libvirt_defaults_libvirtd |
      combine( libvirt_libvirtd, recursive=True ) }}"

- name: merge qemu config configuration between defaults and custom
  set_fact:
    libvirt_qemu: "{{ libvirt_defaults_qemu |
      combine( libvirt_qemu, recursive=True ) }}"

...
