---

- name: ensure libvirtd is enabled on boot
  become: true
  ansible.builtin.service:
    name: "{{ libvirt_service.name }}"
    enabled: true
    state: started

...


# /usr/lib/systemd/system/libvirt-dbus.service
# /usr/lib/systemd/system/libvirtd.service
# /usr/lib/systemd/system/libvirt-guests.service
# /usr/lib/systemd/system/virtchd.service
# /usr/lib/systemd/system/virtinterfaced.service
# /usr/lib/systemd/system/virtlockd.service
# /usr/lib/systemd/system/virtlogd.service
# /usr/lib/systemd/system/virtlxcd.service
# /usr/lib/systemd/system/virtnetworkd.service
# /usr/lib/systemd/system/virtnodedevd.service
# /usr/lib/systemd/system/virtnwfilterd.service
# /usr/lib/systemd/system/virtproxyd.service
# /usr/lib/systemd/system/virtqemud.service
# /usr/lib/systemd/system/virtsecretd.service
# /usr/lib/systemd/system/virtstoraged.service
# /usr/lib/systemd/system/virtvboxd.service
