---

libvirt_libvirtd:
  enable_tcp: true
  listen_addr: "{{ ansible_default_ipv4.address }}"
  auth_unix_ro: "none"
  auth_unix_rw: "none"
  # https://libvirt.org/kbase/debuglogs.html#libvirt-daemons-logging-configuration
  log_level: 3
  log_filters:
    - 3:remote
    - 4:event
    - 3:util.json
    - 3:util.object
    - 3:util.dbus
    - 3:util.netlink
    - 3:node_device
    - 3:rpc
    - 3:access
    - 1:*

  log_outputs:
    - 2:file:/var/log/libvirt/libvirtd.log
    - 3:journald

libvirt_storage_pools:
  - name: pool
    uuid: 4b39e9c3-b4b9-49b0-8ef9-9caa3d985410
    path: /var/lib/libvirt/pool
    autostart: true
    state: active

libvirt_virtual_networks:
  - name: NATting
    mode: bridge
    bridge_name: br0
    autostart: true
    state: absent

...
