---

libvirt_libvirtd:
  enable_tcp: true
  listen_addr: "{{ ansible_default_ipv4.address }}"
  auth_unix_ro: "none"
  auth_unix_rw: "none"

libvirt_storage_pools:
  - name: pool
    uuid: 4b39e9c3-b4b9-49b0-8ef9-9caa3d985410
    path: /var/lib/libvirt/pool
    autostart: true
    state: active

libvirt_virtual_networks:
  - name: NATting
    mode: bridge
    bridge_name: br0
    autostart: true
    state: absent

...
