---
- name: ensure storage pool paths exist
  become: true
  file:
    mode: u=rwx,g=rx,o=rx
    path: "{{ item.path }}"
    state: directory
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.path }}"

- name: defining storage pools
  become: true
  virt_pool:
    command: define
    name: "{{ item.name }}"
    xml: "{{ lookup('template', 'etc/libvirt/storage/pool.xml.j2') }}"
  register: libvirt_pools_defined
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }}"

- name: setting state of storage pools
  become: true
  virt_pool:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when: item.state is defined
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }} - state {{ item.state }}"

- name: setting storage pools to autostart
  virt_pool:
    autostart: true
    name: "{{ item.name }}"
  become: true
  when:
    - item.autostart is defined
    - item.autostart
    - (item.state | default("")) == "active"
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }} - autostart {{ item.autostart }}"

- name: setting storage pools to not autostart
  virt_pool:
    autostart: false
    name: "{{ item.name }}"
  become: true
  when:
    - item.autostart is defined
    - not item.autostart
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }} - autostart {{ item.autostart }}"

...
