---

name: code linter

on:
  schedule:
    - cron: "45 1 * * 0"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'main'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "tasks/**"
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "tasks/**"
jobs:
  pycodestyle:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.11"
          - "3.12"

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'ansible-libvirt'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: update pip
        run: |
          python3 -m pip install --upgrade pip

      - name: install pycodestyle
        run: |
          python3 -m pip install pycodestyle

      - name: run pycodestyle
        run: |
          pycodestyle --config=.config/pycodestyle.cfg --statistics --count --exclude=test_*.py .

  yamllint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'ansible-libvirt'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install yamllint
        run: |
          python3 -m pip install yamllint
          python3 -m pip install ansible-lint

      - name: run yamllint
        run: |
          yamllint .

  ansible-lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'ansible-libvirt'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install ansible-lint
        run: |
          python3 -m pip install ansible-lint

      - name: run ansible lint
        run:
          ansible-lint .

...
